# Generated by Django 5.2.13 on 2026-04-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='sensor_type',
            field=models.CharField(choices=[('PH', 'Potencial de Hidrógeno (pH)'), ('EC', 'Conductividad Eléctrica (EC)'), ('WATER_TEMP', 'Temperatura del Agua'), ('AIR_TEMP', 'Temperatura Ambiental'), ('HUMIDITY', 'Humedad Ambiental'), ('SOIL_MOISTURE', 'Humedad de Suelo/Sustrato'), ('WATER_LEVEL', 'Nivel de Tanque')], max_length=30, verbose_name='Tipo de sensor'),
        ),
    ]
