# Generated by Django 5.2.13 on 2026-04-30 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_sensor_sensor_type'),
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='farms.zone'),
        ),
    ]
