# Generated by Django 5.2.13 on 2026-04-24 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Cultivo')),
                ('scientific_name', models.CharField(blank=True, max_length=100, verbose_name='Nombre Científico')),
                ('duration_days', models.PositiveIntegerField(default=15, verbose_name='Duración del Ciclo (Días)')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Cultivo',
                'verbose_name_plural': 'Tipos de Cultivos',
                'db_table': 'tipo_cultivo',
            },
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre de la Instalación')),
                ('location', models.CharField(max_length=150, verbose_name='Ubicación')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Instalación Hidropónica',
                'verbose_name_plural': 'Instalaciones Hidropónicas',
                'db_table': 'granja',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Módulo')),
                ('code', models.SlugField(unique=True, verbose_name='Código de Módulo')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio de ciclo')),
                ('current_stage', models.CharField(choices=[('GERMINATION', 'Germinación / Plántula'), ('GROWTH', 'Crecimiento Vegetativo'), ('FLOWERING', 'Floración / Fruto'), ('HARVEST', 'Listo para Cosecha')], default='GERMINATION', max_length=20, verbose_name='Etapa actual')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('crop_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='zones', to='farms.croptype', verbose_name='Tipo de Cultivo')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='farms.farm', verbose_name='Instalación')),
            ],
            options={
                'verbose_name': 'Módulo Hidropónico',
                'verbose_name_plural': 'Módulos Hidropónicos',
                'db_table': 'zona',
            },
        ),
    ]
