# Generated by Django 5.2.13 on 2026-04-24 22:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IrrigationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre de la Regla')),
                ('min_threshold', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Umbral mínimo')),
                ('max_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Umbral máximo')),
                ('duration_minutes', models.PositiveIntegerField(default=5, verbose_name='Duración de acción (minutos)')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='devices.sensor')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='farms.zone')),
            ],
            options={
                'verbose_name': 'Regla de Automatización',
                'verbose_name_plural': 'Reglas de Automatización',
                'db_table': 'Configuracion',
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor medido')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='devices.sensor')),
            ],
            options={
                'verbose_name': 'Lectura de Sensor',
                'verbose_name_plural': 'Lecturas de Sensores',
                'db_table': 'lectura',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SystemAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('title', models.CharField(max_length=150, verbose_name='Título de Alerta')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('severity', models.CharField(choices=[('INFO', 'Informativa'), ('WARNING', 'Advertencia'), ('CRITICAL', 'Crítica')], default='WARNING', max_length=20)),
                ('acknowledged', models.BooleanField(default=False)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farms.zone')),
            ],
            options={
                'verbose_name': 'Alerta del Sistema',
                'verbose_name_plural': 'Alertas del Sistema',
                'db_table': 'alerta_sistema',
            },
        ),
        migrations.CreateModel(
            name='SystemEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción del evento')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('actuator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='devices.actuator')),
                ('reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='automation.sensorreading')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='farms.zone')),
            ],
            options={
                'verbose_name': 'Evento del Sistema',
                'verbose_name_plural': 'Eventos del Sistema',
                'db_table': 'evento',
            },
        ),
    ]
