# Generated by Django 5.2.13 on 2026-04-25 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre del Rol')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre del Recurso')),
                ('url_backend', models.CharField(blank=True, max_length=45, verbose_name='URL Backend')),
                ('url_frontend', models.CharField(blank=True, max_length=45, verbose_name='URL Frontend / Ruta')),
                ('path', models.CharField(blank=True, max_length=45, verbose_name='Path')),
                ('icono', models.CharField(blank=True, max_length=45, verbose_name='Ícono (FontAwesome)')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden en menú')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('recurso_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subrecursos', to='core.recurso', verbose_name='Recurso Padre')),
            ],
            options={
                'verbose_name': 'Recurso del Sistema',
                'verbose_name_plural': 'Recursos del Sistema',
                'db_table': 'Recurso',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='RecursoHasRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recurso', models.ForeignKey(db_column='Recurso_idRecursos', on_delete=django.db.models.deletion.CASCADE, related_name='accesos', to='core.recurso', verbose_name='Recurso')),
                ('rol', models.ForeignKey(db_column='rol_idrol', on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='core.rol', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Permiso de Recurso',
                'verbose_name_plural': 'Permisos de Recursos',
                'db_table': 'Recurso_has_rol',
                'unique_together': {('recurso', 'rol')},
            },
        ),
        migrations.AddField(
            model_name='recurso',
            name='roles',
            field=models.ManyToManyField(related_name='recursos', through='core.RecursoHasRol', to='core.rol', verbose_name='Roles con acceso'),
        ),
        migrations.CreateModel(
            name='UsuarioHasRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.ForeignKey(db_column='rol_idrol', on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_asignados', to='core.rol', verbose_name='Rol')),
                ('usuario', models.ForeignKey(db_column='usuario_idusuarios', on_delete=django.db.models.deletion.CASCADE, related_name='roles_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Rol de Usuario',
                'verbose_name_plural': 'Roles de Usuarios',
                'db_table': 'usuario_has_rol',
                'unique_together': {('usuario', 'rol')},
            },
        ),
    ]
