# Generated by Django 5.2.13 on 2026-04-24 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actuator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Actuador')),
                ('actuator_type', models.CharField(choices=[('PUMP', 'Bomba de Riego'), ('OXYGENATOR', 'Oxigenador'), ('DOSER', 'Dosificador de Nutrientes'), ('FAN', 'Ventilador')], max_length=20, verbose_name='Tipo')),
                ('pin', models.CharField(blank=True, max_length=20, verbose_name='Pin')),
                ('state', models.BooleanField(default=False, verbose_name='Estado Actual (ON/OFF)')),
            ],
            options={
                'verbose_name': 'Actuador',
                'verbose_name_plural': 'Actuadores',
                'db_table': 'actuador',
            },
        ),
        migrations.CreateModel(
            name='ActuatorStateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('state', models.BooleanField(default=False, verbose_name='Estado')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actuator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='devices.actuator')),
            ],
            options={
                'verbose_name': 'Historial de Actuador',
                'verbose_name_plural': 'Historial de Actuadores',
                'db_table': 'estado_bomba',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('device_id', models.CharField(max_length=50, unique=True, verbose_name='ID del Dispositivo')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('firmware_version', models.CharField(blank=True, max_length=50, verbose_name='Versión de firmware')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='farms.zone')),
            ],
            options={
                'verbose_name': 'Controlador IoT',
                'verbose_name_plural': 'Controladores IoT',
                'db_table': 'Dispositivo',
            },
        ),
        migrations.AddField(
            model_name='actuator',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actuators', to='devices.device'),
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Sensor')),
                ('sensor_type', models.CharField(choices=[('PH', 'Potencial de Hidrógeno (pH)'), ('EC', 'Conductividad Eléctrica (EC)'), ('WATER_TEMP', 'Temperatura del Agua'), ('AIR_TEMP', 'Temperatura Ambiental'), ('HUMIDITY', 'Humedad Ambiental'), ('WATER_LEVEL', 'Nivel de Tanque')], max_length=30, verbose_name='Tipo de sensor')),
                ('unit', models.CharField(max_length=20, verbose_name='Unidad')),
                ('pin', models.CharField(blank=True, max_length=20, verbose_name='Pin de conexión')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='devices.device')),
            ],
            options={
                'verbose_name': 'Sensor',
                'verbose_name_plural': 'Sensores',
                'db_table': 'sensor',
            },
        ),
    ]
